package com.vvxc.bos.bean;
// Generated 2017-5-12 22:45:22 by Hibernate Tools 3.4.0.CR1

/**
 * BcSubarea generated by hbm2java
 */
public class Subarea implements java.io.Serializable {

	private String id;
	private Region region;
	private Decidedzone decidedzone;
	
	public String  getSubareaId() {
		return id;
	}
	public Decidedzone getDecidedzone() {
		return decidedzone;
	}

	public void setDecidedzone(Decidedzone decidedzone) {
		this.decidedzone = decidedzone;
	}

	private String addresskey;
	private String startnum;
	private String endnum;
	private Character single;
	private String position;

	public Subarea() {
	}

	public Subarea(String id) {
		this.id = id;
	}

	public Subarea(String id, Region bcRegion, Decidedzone bcDecidedzone,
			String addresskey, String startnum, String endnum,
			Character single, String position) {
		this.id = id;
		this.region = bcRegion;
		this.decidedzone = bcDecidedzone;
		this.addresskey = addresskey;
		this.startnum = startnum;
		this.endnum = endnum;
		this.single = single;
		this.position = position;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region bcRegion) {
		this.region = bcRegion;
	}


	public String getAddresskey() {
		return this.addresskey;
	}

	public void setAddresskey(String addresskey) {
		this.addresskey = addresskey;
	}

	public String getStartnum() {
		return this.startnum;
	}

	public void setStartnum(String startnum) {
		this.startnum = startnum;
	}

	public String getEndnum() {
		return this.endnum;
	}

	public void setEndnum(String endnum) {
		this.endnum = endnum;
	}

	public Character getSingle() {
		return this.single;
	}

	public void setSingle(Character single) {
		this.single = single;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

}
