package com.vvxc.bos.bean;

// Generated 2017-5-25 23:35:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * QpWorkbill generated by hbm2java
 */
public class Workbill implements java.io.Serializable {

	private String id;
	private Noticebill noticebill;
	private Staff staff;
	private String type;
	private String pickstate;
	private Date buildtime;
	private Integer attachbilltimes;
	private String remark;

	public Workbill() {
	}

	public Workbill(String id, Date buildtime) {
		this.id = id;
		this.buildtime = buildtime;
	}

	public Workbill(String id, Noticebill noticebill, Staff staff,
			String type, String pickstate, Date buildtime,
			Integer attachbilltimes, String remark) {
		this.id = id;
		this.noticebill = noticebill;
		this.staff=staff;
		this.type = type;
		this.pickstate = pickstate;
		this.buildtime = buildtime;
		this.attachbilltimes = attachbilltimes;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Noticebill getNoticebill() {
		return this.noticebill;
	}

	public void setNoticebill(Noticebill noticebill) {
		this.noticebill = noticebill;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPickstate() {
		return this.pickstate;
	}

	public void setPickstate(String pickstate) {
		this.pickstate = pickstate;
	}

	public Date getBuildtime() {
		return this.buildtime;
	}

	public void setBuildtime(Date buildtime) {
		this.buildtime = buildtime;
	}

	public Integer getAttachbilltimes() {
		return this.attachbilltimes;
	}

	public void setAttachbilltimes(Integer attachbilltimes) {
		this.attachbilltimes = attachbilltimes;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
